"""Unit tests for inputs generated by an untrusted model."""

import sys
import unittest
from pathlib import Path
from uuid import uuid4

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ai_native_linux.contracts import RiskLevel, SystemMetric
from ai_native_linux.policy import PolicyEngine, PolicyViolation


def valid_payload() -> dict[str, object]:
    return {
        "request_id": str(uuid4()),
        "intent": "get_system_status",
        "arguments": {"metrics": ["disk", "memory", "cpu"], "process_limit": 10},
        "reason": "Пользователь хочет увидеть текущую нагрузку.",
    }


class PolicyEngineTests(unittest.TestCase):
    def setUp(self) -> None:
        self.engine = PolicyEngine()

    def test_allows_valid_read_only_status_request(self) -> None:
        proposal, decision = self.engine.evaluate(valid_payload())

        self.assertEqual(proposal.metrics, (SystemMetric.DISK, SystemMetric.MEMORY, SystemMetric.CPU))
        self.assertEqual(decision.tool, "ubuntu.system.status.read")
        self.assertEqual(decision.risk_level, RiskLevel.READ_ONLY)
        self.assertFalse(decision.approval_required)

    def test_rejects_unallowlisted_intent(self) -> None:
        payload = valid_payload()
        payload["intent"] = "run_shell_command"

        with self.assertRaises(PolicyViolation):
            self.engine.evaluate(payload)

    def test_rejects_unknown_argument(self) -> None:
        payload = valid_payload()
        arguments = payload["arguments"]
        assert isinstance(arguments, dict)
        arguments["shell_command"] = "rm -rf /"

        with self.assertRaises(PolicyViolation):
            self.engine.evaluate(payload)

    def test_rejects_invalid_process_limit(self) -> None:
        payload = valid_payload()
        arguments = payload["arguments"]
        assert isinstance(arguments, dict)
        arguments["process_limit"] = 21

        with self.assertRaises(PolicyViolation):
            self.engine.evaluate(payload)


if __name__ == "__main__":
    unittest.main()
